<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FCB1010.Core\FCB1010.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Melanchall.DryWetMidi" Version="8.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
